services:
  elk:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NUXT_PUBLIC_TRANSLATE_API: "https://translate.manganiello.tech/translate"
    volumes:
      # make sure this directory has the same ownership as the elk user from the Dockerfile
      # otherwise Elk will not be able to store configs for accounts
      # e.g., mkdir ./elk-storage; sudo chown 911:911 ./elk-storage
      - './elk-storage:/elk/data'
    ports:
      - 5314:5314
