[build]
  publish = "dist"
  command = "pnpm run build && pnpm run test && pnpm run lint && pnpm test:typecheck"

# Redirect to Discord server
[[redirects]]
  from = "https://chat.elk.zone"
  to = "https://discord.gg/vAZSDU9J"
  status = 301
  force = true

[[rewrites]]
  from = "/*"
  to = "/index.html"
  status = 200
